version: 2
updates:
  - package-ecosystem: pip
    directory: "/04_桌面桌宠程序/01_程序源码"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
