"""Native 2.5D game rendering. Source art is immutable; chroma is composited in memory."""
import math
from functools import lru_cache
from pathlib import Path

from PySide6.QtCore import Qt, QPointF, QRectF
from PySide6.QtGui import QImage, QPixmap, QPainter, QPen, QColor, QRadialGradient, QFont


@lru_cache(maxsize=4)
def load_character(path):
    """Prepare a reusable RGBA texture, retaining soft fur coverage.

    This is a normal chroma-key material in the game's renderer, not a rewritten
    or background-edited source file. Fully opaque checkerboard assets are rejected.
    """
    source = QImage(str(path))
    if source.isNull():
        return None
    source = source.convertToFormat(QImage.Format.Format_RGBA8888)
    # The source is intentionally authored on saturated green for this material.
    corner = source.pixelColor(0, 0)
    keyed = corner.green() > 180 and corner.green() > max(corner.red(), corner.blue()) + 90
    if not keyed and not source.hasAlphaChannel():
        return None
    pixels = bytearray(source.constBits())
    if keyed:
        for i in range(0, len(pixels), 4):
            red, green, blue = pixels[i:i + 3]
            difference = green - max(red, blue)
            if difference > 10:
                # White fur mixed with the known green backdrop: remove key
                # contribution, then unpremultiply to keep fine white hairs white.
                alpha = max(0., min(1., 1. - difference / 255.))
                if alpha < .04:
                    pixels[i:i + 4] = b'\x00\x00\x00\x00'
                else:
                    pixels[i] = min(255, round(red / alpha))
                    pixels[i + 1] = min(255, round(max(red, blue) / alpha))
                    pixels[i + 2] = min(255, round(blue / alpha))
                    pixels[i + 3] = round(alpha * 255)
    texture = QImage(pixels, source.width(), source.height(), source.bytesPerLine(), QImage.Format.Format_RGBA8888).copy()
    return QPixmap.fromImage(texture)


def paint_character(canvas, painter, pixmap):
    """Small restrained motions keep photographed anatomy and paw contact intact."""
    p = painter
    p.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform)
    w, h = canvas.width(), canvas.height()
    side = min(w, h)
    x, y = (w - side) / 2, h - side
    clock = canvas.phase / 2.4
    sleeping = canvas.behavior == "sleeping"
    amplitude = .003 if sleeping else .0045
    breath = math.sin(clock * (1.5 if sleeping else 2.1)) * amplitude
    pose_x, pose_y, pose_angle = canvas.pose
    bx, by, angle, dx, dy = canvas.body_pose
    p.save()
    anchor = QPointF(x + side * .51, y + side * .94)
    p.translate(anchor)
    p.rotate(pose_angle + angle)
    p.scale(pose_x * bx, pose_y * by * (1 + breath))
    p.translate(-anchor.x() + dx, -anchor.y() + dy)
    if canvas.behavior == "playing":
        p.translate(0, -abs(math.sin(clock * 3.4)) * side * .018)
    # A translucent contact shadow is generated by the renderer, not baked into art.
    shadow = QRadialGradient(QPointF(x + side * .52, y + side * .93), side * .20)
    shadow.setColorAt(0, QColor(45, 40, 33, 40))
    shadow.setColorAt(1, QColor(45, 40, 33, 0))
    p.setPen(Qt.PenStyle.NoPen)
    p.setBrush(shadow)
    p.drawEllipse(QRectF(x + side * .29, y + side * .90, side * .46, side * .055))
    p.drawPixmap(QRectF(x, y, side, side), pixmap, QRectF(pixmap.rect()))
    p.restore()
    # Props are interaction feedback. No painted replacement dog limbs or face.
    if canvas.behavior in ("eating", "snacking"):
        p.setPen(Qt.PenStyle.NoPen)
        p.setBrush(QColor("#b38b73"))
        p.drawRoundedRect(QRectF(w * .39, h * .91, w * .22, h * .055), 6, 6)
        p.setBrush(QColor("#d8beaa"))
        p.drawEllipse(QRectF(w * .39, h * .90, w * .22, h * .028))
    elif canvas.behavior == "playing":
        p.setPen(QPen(QColor("#b79062"), 1))
        p.setBrush(QColor("#d6b076"))
        p.drawEllipse(QRectF(w * .80, h * .86 - abs(math.sin(clock * 3)) * 12, 18, 18))
    elif sleeping:
        p.setPen(QColor("#89967c"))
        p.setFont(QFont("Georgia", 13))
        p.drawText(QPointF(w * .82, h * .22), "z z")
